### ISSUE TITLE
Needs a review/edit

### ISSUE THREAD

**Issue by lauracowen** [OpenLiberty/guide-microprofile-opentracing-jaeger#21]
I've not read this whole guide but it seems really long for what it is (the intro is really long and the sections seem very wordy) - is it trying to document the whole of this rather than tell a single story?

It also seems to be using a bit of an odd/inconsistent approach to the app by saying the app provided for you and you just enable tracing - that's not how we present the apps in guides - the user should be creating the app and, in this case, enabling tracing (we _always_ provide the app in every guide, but we don't present it that way). So the "update" actions should be "create" actions, then the relevant bit that's explained is the trace annotations (or whatever) in the code.

eg in this section: https://openliberty.io/guides/microprofile-opentracing-jaeger.html#enabling-explicit-distributed-tracing

**Comment by gkwan-ibm** [comment]
close
- this guide was deprecated
