### ISSUE TITLE
Update to use MP OT 2.0

### ISSUE THREAD

**Issue by Emily-Jiang** [OpenLiberty/guide-microprofile-opentracing-jaeger#25]

**Comment by gkwan-ibm** [comment]
only update the pom.xml and server.xml to latest versions, see https://github.com/openliberty/guide-microprofile-opentracing/issues/127#issuecomment-758924142

**Comment by gkwan-ibm** [comment]
close
- the [guide](https://openliberty.io/guides/microprofile-opentracing-jaeger.html) was updated
